### Generate access token
POST http://localhost:8787/realms/test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=caju@cajucomunica.com.br
&password=password
&grant_type=password
&client_id=api

### Generate access token and id token
POST http://localhost:8787/realms/test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=caju@cajucomunica.com.br
&password=password
&grant_type=password
&client_id=api
&scope=openid

### Well-known configuration
GET http://localhost:8787/realms/test/.well-known/openid-configuration
