@hostname = localhost
@port = 8888
@baseUrl = http://{{hostname}}:{{port}}
@contentType = application/json
@userAgent = insomnia/8.5.1

### POST /users
# @name createuser
POST {{baseUrl}}/users HTTP/1.1
Content-Type: {{contentType}}
User-Agent: {{userAgent}}

{
	"name": "John Doe",
	"email": "johndoe@email.com",
	"password": "12345678"
}

# @userId = {{createuser.response.body.id}}

### PUT /users
# @name updateuser
PATCH {{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
User-Agent: {{userAgent}}

{
	"name": "Jane Doe",
	"email": "janedoe@email.com",
	"password": "12345678"
}

### GET /users
# @name getusers
GET {{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
User-Agent: {{userAgent}}

### ==================== Keycloak ==================== ###
### Generate access token
POST http://localhost:8787/realms/test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=caju@cajucomunica.com.br
&password=password
&grant_type=password
&client_id=api

### Generate access token and id token
POST http://localhost:8787/realms/test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=caju@cajucomunica.com.br
&password=password
&grant_type=password
&client_id=api
&scope=openid

### Well-known configuration
GET http://localhost:8787/realms/test/.well-known/openid-configuration
