version: '3'

services:

  keycloak-postgres:
    image: postgres:latest
    container_name: keycloak-postgres
    platform: linux/x86_64
    restart: always
    tty: true
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./databases/dumps/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
      - ./databases/postgres:/var/lib/postgresql/data

  keycloak-study:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: keycloak-study
    command: start-dev
    ports:
      - 8787:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    volumes:
      - ./keycloak/keywind/theme/keywind:/opt/keycloak/themes/keywind
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    networks:
      - keycloak-network

  keycloak-mysql:
    image: mysql:8.0.30-debian
    container_name: keycloak-mysql
    platform: linux/x86_64
    volumes:
      - ./databases/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - keycloak-network

networks:
  keycloak-network:
    external: true
